#!/usr/bin/env python3

from pathlib import Path
import subprocess
import requests
import argparse
import logging
import zipfile
import signal
import shutil
import sys

# Config logs
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)

# Config args
parser = argparse.ArgumentParser(
  description="""Script to download timezone polygon zip file and build timezone polygon database""",
)

parser.add_argument(
  "--force",
  action="store_true",
  help="Force delete existing timezone polygon zip file and redownload",
  default=False,
)
parser.add_argument(
  "--prefix",
  help="Prefix of path to the data folders",
  type=Path,
  default="data",
)


if __name__ == "__main__":
  signal.signal(signal.SIGINT, lambda sig, frame: (
    LOGGER.info('Received "SIGINT" signal. Exitting...'),

    sys.exit(0)
  ))

  signal.signal(signal.SIGTERM, lambda sig, frame: (
    LOGGER.info('Received "SIGTERM" signal. Exitting...'),

    sys.exit(0)
  ))

  args = parser.parse_args()

  tz_polygon_db_file_path = Path(f"{args.prefix}/timezone/timezone.sqlite")
  tz_polygon_zip_file_path = Path(f"{args.prefix}/timezone/timezone.zip")
  tz_polygon_unzip_dir_path = Path(f"{args.prefix}/timezone/timezone")

  if not args.force:
    if not tz_polygon_zip_file_path.exists():
      LOGGER.error(f"Missing timezone polygon zip file {tz_polygon_zip_file_path}")

      sys.exit(1)
    else:
      LOGGER.info(f"Found timezone polygon zip file {tz_polygon_zip_file_path}")
  else:
    try:
      tz_polygon_file_url = "https://github.com/evansiroky/timezone-boundary-builder/releases/download/2024a/timezones-with-oceans.shapefile.zip"

      LOGGER.info(f"Downloading timezone polygon zip file from {tz_polygon_file_url}...")

      with requests.get(tz_polygon_file_url, stream=True) as r:
        r.raise_for_status()

        with open(tz_polygon_zip_file_path, "wb") as f:
          for chunk in r.iter_content(chunk_size=10*1024*1024):
            if chunk:
              f.write(chunk)
    except Exception as e:
      LOGGER.error(f"Failed to download timezone polygon zip file from {tz_polygon_file_url}: {e}")

      sys.exit(1)

  try:
    LOGGER.info(f"Unzipping timezone polygon zip file {tz_polygon_zip_file_path}...")

    with zipfile.ZipFile(tz_polygon_zip_file_path, "r") as z:
      z.extractall(tz_polygon_unzip_dir_path)
  except Exception as e:
    LOGGER.error(f"Failed to unzipping timezone polygon zip file {tz_polygon_zip_file_path}: {e}")

    sys.exit(1)

  try:
    LOGGER.info(f"Creating timezone polygon database from {tz_polygon_unzip_dir_path}...")

    if tz_polygon_db_file_path.exists():
      tz_polygon_db_file_path.unlink()

    tz_polygon_shp_file = None
    for file in tz_polygon_unzip_dir_path.glob("*.shp"):
      tz_polygon_shp_file = file.stem

    if not tz_polygon_shp_file:
      LOGGER.error(f"No timezone polygon shapefile found in {tz_polygon_unzip_dir_path}")

      sys.exit(1)
    else:
      subprocess.run(f"spatialite_tool -i -shp {tz_polygon_unzip_dir_path}/{tz_polygon_shp_file} -d {tz_polygon_db_file_path} -t timezone -s 4326 -g geom -c UTF-8", check=True, shell=True)

      subprocess.run(f"spatialite {tz_polygon_db_file_path} \"SELECT CreateSpatialIndex('timezone', 'geom')\"", check=True, shell=True)

      subprocess.run([f"spatialite {tz_polygon_db_file_path} \"VACUUM\""], check=True, shell=True)

      subprocess.run([f"spatialite {tz_polygon_db_file_path} \"ANALYZE\""], check=True, shell=True)

    shutil.rmtree(tz_polygon_unzip_dir_path)
  except Exception as e:
    LOGGER.error(f"Failed to creating timezone polygon database from {tz_polygon_unzip_dir_path}: {e}")

    sys.exit(1)

  LOGGER.info(f"Finished to creating timezone polygon database")
