#!/usr/bin/env python3

from pathlib import Path
import argparse
import logging
import shutil
import sys

# Config logs
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)

# Config args
parser = argparse.ArgumentParser(
  description="""Script to delete data folders and config file""",
)

parser.add_argument(
  "-p",
  "--prefix",
  help="Prefix of path to the data folders",
  type=Path,
  default="data",
)


if __name__ == "__main__":
  args = parser.parse_args()

  try:
    shutil.rmtree(args.prefix)
  except Exception as e:
    LOGGER.error(f"Failed to deleting data folders and config file at {args.prefix}: {e}.")

    sys.exit(1)
