#!/usr/bin/env python3

from pathlib import Path
import argparse
import logging
import shutil
import sys

# Config logs
LOGGER = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)5s: %(message)s"))
LOGGER.addHandler(handler)
LOGGER.setLevel(logging.INFO)

# Config args
parser = argparse.ArgumentParser(
  description="""Script to create data folders""",
)

parser.add_argument(
  "-f",
  "--force",
  action="store_true",
  help="Force delete all existing data folders and recreate",
  default=False,
)
parser.add_argument(
  "-p",
  "--prefix",
  help="Prefix of path to the data folders",
  type=Path,
  default="data",
)


if __name__ == "__main__":
  args = parser.parse_args()

  try:
    if args.force:
      shutil.rmtree(args.prefix)

    LOGGER.info(f"Creating data folders at {args.prefix}...")

    for dir in ["osms", "tiles", "transit", "traffic", "landmarks", "admin", "timezone", "transit_feeds", "elevation_tiles", "logs"]:
      Path(f"{args.prefix}/{dir}").mkdir(parents=True, exist_ok=True)

  except Exception as e:
    LOGGER.error(f"Failed to creating data folders at {args.prefix}: {e}.")

    sys.exit(1)
